### ISSUE TITLE
minimum-stability

### ISSUE THREAD

**Issue by t202wes** [FoxxMD/laravel-elasticbeanstalk-cron#1]
`composer require "foxxmd/laravel-elasticbeanstalk-cron`

> You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> 
>   [InvalidArgumentException]  
>   Could not find package foxxmd/laravel-elasticbeanstalk-cron at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
>

**Comment by FoxxMD** [comment]
Since I do not have any tests or other metrics proving stability I don't feel comfortable marking this package as stable. Keeping it as dev is a sign to other developers/users that this is untested code and should be used at your own risk (fork it if it has problems!)

However you can easily set the stability for this package in composer.json:

``` json
{
    "require": {
        "foxxmd/laravel-elasticbeanstalk-cron": "*@dev",
    },
}
```

and if you're okay with dev as minimum-stability I put out a "stable" release:

``` json
{
    "require": {
        "foxxmd/laravel-elasticbeanstalk-cron": "0.2",
    },
}
```

Let me know if this works for you

**Comment by Jono20201** [comment]
FYI: Some people may want to target the latest commit as of time of posting to ensure they don't get a surprise update one date. Just got to manually come back and check for updates sometimes.

``` json
{
    "require": {
        "foxxmd/laravel-elasticbeanstalk-cron": "dev-master#c8adc3b8acacb72ae4425181e263e8171b4388ea",
    },
}
```

**Comment by FoxxMD** [comment]
@Jono20201 I've made a [release](https://github.com/FoxxMD/laravel-elasticbeanstalk-cron/releases/tag/0.1) to make it less of a pain to pin to a stable commit. Sorry for the inconvenience! 

``` php
{
    "require": {
        "foxxmd/laravel-elasticbeanstalk-cron": "0.2",
    },
}
```

**Comment by Jono20201** [comment]
@FoxxMD,

No worries, this package managed to save me doing some really odd stuff yesterday to try and find a solution to this issue. I hate the idea of having end points to trigger commands. Just feels icky. So thanks for the package.

If I find time I will try and contribute some tests to help stability. The AWS client will have to be mocked somehow.

Thanks again!

**Comment by FoxxMD** [comment]
@Jono20201 

>  I hate the idea of having end points to trigger commands. Just feels icky.

I agree but TBH this approach isn't airtight either. I noticed over a long period of use I would get weird error back from AWS (`describeInstances` coming back with an empty list, as an example) that was causing more pain than it was worth. 

I've switched to using the AWS method which still doesn't feel great but I've mitigated most of my concerns by adding some extra security on top of the job endpoints and also replicating the "email output" feature of laravel's scheduler in my console commands. It also seems to be more reliable. One of these days soon I'll write up another package with those modifications.

**Comment by Jono20201** [comment]
@FoxxMD Thanks for the info, we'll see how it goes and then consider our options as we go. I've been running a standalone EC2 instance for the last two years tasked with purely cron jobs, and with updating to PHP7 I wanted to move cron jobs into ELB/CodeDeploy.

**Comment by t202wes** [comment]
Yes, thank you for this package @FoxxMD.
