### ISSUE TITLE
Artisan executed as root.

### ISSUE THREAD

**Issue by heathdutton** [FoxxMD/laravel-elasticbeanstalk-cron#10]
It is possible with the example config that artisan is eventually executed as root (by cron), which can be rather bad. This is important if you are following the Laravel recommendations for permissions. Example:
```container_commands:
  41_laravel_set_permissions:
    command: sudo chown -R webapp:webapp .
  42_laravel_set_permissions:
    command: sudo chgrp -R webapp storage themes
  43_laravel_set_permissions:
    command: sudo chmod -R ug+wx storage themes
  44_laravel_set_permissions:
    test: test -d "bootstrap/cache"
    command: sudo chgrp -R webapp bootstrap/cache
  45_laravel_set_permissions:
    test: test -d "bootstrap/cache"
    command: sudo chmod -R ug+wx bootstrap/cache
```

Using the above means that Laravel will always run as webapp (good). However, if the cron task runs early in the morning creating a new log file (daily mode), the application would not be able to append to it later (because it would be created as root), possibly causing critical downtime when logging info-level.

**Comment by heathdutton** [comment]
Updated the PR.

Didn't realize that if you execute php as webapp, but there is no /home/webapp directory, the cron tasks generated will be defaulted to root ownership (or fail w/ an error). Yikes.

So added a home directory for webapp (if it doesn't already exist) to prevent that.

**Comment by FoxxMD** [comment]
> if you are following the Laravel recommendations for permissions.

Where are these recommendations? 

I'm wary about changing any permissions, have you tested any of this on your own projects?

**Comment by heathdutton** [comment]
We're following examples like this:
https://laracasts.com/discuss/channels/general-discussion/laravel-framework-file-permission-security
Plus some examples for octoberCMS. And we're running the above in production for some pretty big sites without troubles.

If the application is being ran as webapp via apache, then running it as webapp in cron should be a safe bet. That being said, this doesn't take into account how someone might use a custom docker container... Who knows, they might not have a webapp user? Hmm. Maybe this should be configurable instead?
