### ISSUE TITLE
Error after deploy running "runLeaderSelection"

### ISSUE THREAD

**Issue by paulhuisman** [FoxxMD/laravel-elasticbeanstalk-cron#17]
Hey,

I tried adding your plugin and getting the following error in Beanstalk:

`Application update failed at 2018-05-14T08:56:01Z with exit status 1 and error: container_command runLeaderSelection in .ebextensions/99scheduler.config failed.`

I added the config, env variables etc.

Any idea what's missing?

**Comment by dawolf** [comment]
We are running into a similar problem. How did you fix this in your case @paulhuisman ?
