### ISSUE TITLE
No longer needed

### ISSUE THREAD

**Issue by t202wes** [FoxxMD/laravel-elasticbeanstalk-cron#2]
I absolutely love what you created, but now AWS has an official way to manage cronjobs. It requires a worker-tier, but it works. http://stackoverflow.com/a/28719447/2268516

**Comment by FoxxMD** [comment]
Thanks! I actually link to that answer in the second paragraph of the readme 😛

Amazon's solution is fine but it still requires setup -- namely you need to create a route/controller for handling job execution through a request. This could (and should) also require authentication of some type on your part to ensure no one else can arbitrary execute jobs through that route. Arguably this doesn't take much effort, but it's still more work than no work.

The point of this project is to allow **zero-setup** use of the built in laravel scheduler with EB. It's an alternative to the "official way". It may be no longer needed for you, but I'm sure it's still useful to someone :)
