### ISSUE TITLE
Laravel 6,7,8 Support

### ISSUE THREAD

**Issue by MichaelHoughton** [FoxxMD/laravel-elasticbeanstalk-cron#21]
I just wanted to check if there was an interest for this library to support Laravel 6,7 and 8?

It should be simple enough to upgrade.

**Comment by FoxxMD** [comment]
I am no longer using this library and am not involved in any laravel development using those versions. If you would like to submit a PR updating it I'd be happy to accept.

**Comment by MichaelHoughton** [comment]
@FoxxMD - thanks for this.  I have submitted 3 PR's for the 3 different Laravel versions.  You could likely tag each one so that there is an upgrade available for all 3 versions of Laravel.

**Comment by FoxxMD** [comment]
Thanks @MichaelHoughton! I have merged all your PRs and tagged them respectively.

**Comment by MichaelHoughton** [comment]
Thanks @FoxxMD - nice one.
