### ISSUE TITLE
Cannot access environment variable on Amazon Linux 2

### ISSUE THREAD

**Issue by Ali-Shaikh** [FoxxMD/laravel-elasticbeanstalk-cron#25]
This is failing on AMI 2 as the location of env variables has changed to /opt/elasticbeanstalk/deployment/env. Please refer to the post below

https://aws.amazon.com/premiumsupport/knowledge-center/elastic-beanstalk-env-variables-linux2/

I will be exploring this in detail and see if I can find a working solution

**Comment by FoxxMD** [comment]
Please let me know what you find. I do not use any AMI 2 instances with this project so I cannot support it.

**Comment by Ali-Shaikh** [comment]
Took me a couple of days but I managed to figure it out https://github.com/AWSomeTech/aws-eb-laravel

**Comment by Ali-Shaikh** [comment]
[00_set_env.sh](https://github.com/AWSomeTech/aws-eb-laravel/blob/master/.platform/hooks/postdeploy/00_set_env.sh)
[01_create_cron_files.sh](https://github.com/AWSomeTech/aws-eb-laravel/blob/master/.platform/hooks/postdeploy/01_create_cron_files.sh)

**Comment by buddhaCode** [comment]
I have similar problems with the envs.

Maybe this helps: https://aws.amazon.com/de/premiumsupport/knowledge-center/elastic-beanstalk-env-variables-shell/

**Comment by MbahDjoe** [comment]
New [version 1.0](https://github.com/FoxxMD/laravel-elasticbeanstalk-cron/releases/tag/1.0) is released, now it supports Amazon Linux 2
