### ISSUE TITLE
EB config properties

### ISSUE THREAD

**Issue by bendubuisson** [FoxxMD/laravel-elasticbeanstalk-cron#4]
shouldn't `AWS_SECRET_ACCESS_KEY` be `AWS_SECRET_KEY` ?

**Comment by bendubuisson** [comment]
![screen shot 2016-09-28 at 3 44 27 pm](https://cloud.githubusercontent.com/assets/3079189/18899044/8a55ad4a-8592-11e6-9e61-96d6c4c560d5.png)

**Comment by bendubuisson** [comment]
I can see they are using aws_secret_access_key in the .aws folder too, weird...

**Comment by FoxxMD** [comment]
Yeah amazon isn't great at staying consistent with their libraries...
