### ISSUE TITLE
Fails when only one instance for some reason

### ISSUE THREAD

**Issue by bendubuisson** [FoxxMD/laravel-elasticbeanstalk-cron#8]
When there is only one instance it returns a `undefined offset [0]` on https://github.com/FoxxMD/laravel-elasticbeanstalk-cron/blob/master/src/Console/AWS/ConfigureLeaderCommand.php#L104

**Comment by FoxxMD** [comment]
I ran into this once in a while as well. If you find the reason and fix it would you mind making a PR? Thanks

**Comment by bendubuisson** [comment]
Sure. I have forked it and will put a lot of logging aroubd it and try to
figure it out. Thanks

**Comment by Jono20201** [comment]
PR for fix: https://github.com/FoxxMD/laravel-elasticbeanstalk-cron/pull/9

Can we tag 0.2?

**Comment by FoxxMD** [comment]
Thanks @Jono20201 for the work :) Closing this!
